image: microsoft/dotnet:sdk

pipelines:
  branches:
    feature/*:
      - parallel:
          - step:
              name: Latest .net Core 2
              image: microsoft/dotnet:sdk
              caches:
                - dotnetcore
              script:
                - git submodule update --init
                - scripts/common/dotnetcore/buildTestPack.sh
                - scripts/common/git/tagBitbucket.sh
