image: microsoft/dotnet:sdk

pipelines:
  branches:
    feature/*:
      - parallel:
          - step:
              name: Latest .net Core 2
              image: microsoft/dotnet:sdk
              caches:
                - dotnetcore
              script:
                - git submodule update --init
                # call the dotnet test script
                - dotnet restore
                - dotnet build
                - dotnet test
                - dotnet pack --configuration Release
                - ls -al scratch/bin/*/*.nupkg
                - scripts/common/git/tagBitbucket.sh
