image: microsoft/dotnet:sdk

pipelines:
  branches:
    feature/*:
      - parallel:
          - step:
              name: Latest .net Core 2.1
              image: mcr.microsoft.com/dotnet/core/sdk:2.1
              caches:
                - dotnetcore
              script:
                - git submodule update --init
                - scripts/common/dotnetcore/buildTestPack.sh
              # we test on different versions, but the artifact we will publish is built with 2.1
              artifacts:
                - scratch/bin/**/*.nupkg
          - step:
              name: Latest .net Core 2.2
              image: mcr.microsoft.com/dotnet/core/sdk:2.2
              caches:
                - dotnetcore
              script:
                - git submodule update --init
                - scripts/common/dotnetcore/buildTestPack.sh
          - step:
              name: Latest .net Core 3.0
              image: mcr.microsoft.com/dotnet/core/sdk:3.0
              caches:
                - dotnetcore
              script:
                - git submodule update --init
                - scripts/common/dotnetcore/buildTestPack.sh
      - step:
          name: Tag
          image: mcr.microsoft.com/dotnet/core/sdk:2.2
          script:
            - git submodule update --init
            - scripts/common/git/tagBitbucket.sh
