<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- target frameworks -->
        <TargetFrameworks>net60;net80</TargetFrameworks>

        <!-- nuget package -->
        <IsPackable>false</IsPackable>

        <!-- Stylecop -->
        <CodeAnalysisRuleSet>..\StyleCop-Tests.ruleset</CodeAnalysisRuleSet>

        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
        <PackageReference Include="NUnit" Version="4.1.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />

        <!-- logger for test report in junit format -->
        <PackageReference Include="JUnitTestLogger" Version="1.1.0" />

        <!-- logger for test report in nunit format -->
        <PackageReference Include="NunitXml.TestLogger" Version="3.1.20" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\IV\PPWCode.Vernacular.Exceptions.IV.csproj" />
    </ItemGroup>

</Project>
