<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- target frameworks -->
    <TargetFrameworks>netstandard2.0;net60;net80</TargetFrameworks>

    <!-- nuget package -->
    <IsPackable>true</IsPackable>

    <!-- Stylecop -->
    <CodeAnalysisRuleSet>..\StyleCop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

</Project>
