= About

The library `PPWCode.Vernacular.Exceptions.V` is part of the .NET PPWCode project and encapsulates the _vernacular_ on exceptions.

`PPWCode.Vernacular.Exceptions.V` is a helper library that defines a number of base `Exception` classes.  This is generation `V` of the `PPWCode.Vernacular.Exceptions` library.

The library supports the recent .NET SDKs.


== Development

Development of the PPWCode is done on https://github.com/peopleware/net-ppwcode-vernacular-exceptions/tree/V/next[GitHub].

Releases (both stable and pre-release) are published on https://www.nuget.org/packages/PPWCode.Vernacular.Exceptions.V/[NuGet] by https://www.nuget.org/profiles/PeopleWare[PeopleWare].


== License and Copyright

Copyright 2014–2026 by xref:ppwcode-net:ROOT:peopleware.adoc[PeopleWare].

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
