<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common-tests.props"/>

    <PropertyGroup>
        <CodeAnalysisRuleSet>..\StyleCop-Tests.ruleset</CodeAnalysisRuleSet>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\V\PPWCode.Vernacular.Exceptions.V.csproj" />
    </ItemGroup>

</Project>
